that file use for orchestrating a FastAPI application with a MySQL database and Nginx as a reverse proxy.
but we can`t use stable internet connection for downloading images from docker hub.(MYsql)
so that file be empty but that must have shape like this form

#version: "3.9"
#
#services:
#  fastapi:
#    build: .
#    container_name: fastapi
#    restart: always
#    ports:
#      - "8000:8000"
#    depends_on:
#      - db
#    environment:
#      - DATABASE_URL=mysql+pymysql://root:password@db:3306/mydb
#
#  db:
#    image: mysql:8.0
#    container_name: mysql
#    restart: always
#    environment:
#      MYSQL_ROOT_PASSWORD: password
#      MYSQL_DATABASE: mydb
#    ports:
#      - "3306:3306"
#    volumes:
#      - mysql_data:/var/lib/mysql
#
#  nginx:
#    image: nginx:latest
#    container_name: nginx
#    ports:
#      - "80:80"
#    volumes:
#      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
#    depends_on:
#      - fastapi
#
#volumes:
#  mysql_data:
